### ISSUE TITLE
Possibilities to easily import content models

### ISSUE THREAD

**Issue by stefanjudis** [contentful/content-models#8]
Heyooo. 👋 

I think this repo is a great way to share content models but I also believe we could go one step further. Right now this repo acts like a store for content models.

@axe312ger came up with the idea that this model could also provide the "import functionality" so that we could publish it on npm, too.

This has the advantage that boilerplates for e.g. nuxt, next, gatsby, ... could all rely on this setup repository and don't have to deal with more than firing one command or executing one script.

I'm thinking of something like this as the first version (ignoring a CLI way to things for now):

```
const contentModels = require('contentful-content-models')
contentModels.import('blog', { accessToken, spaceId })
  .then( _ => console.log('yeah'))
```

Shipping the content models via npm would also mean, that we can install them via npm and don't have to write download functionality ourselves.

Does the proposed API look okay, for you folks? I'd love to tackle it in the near future. :)

Any opinions? @axe312ger @floelhoeffel @Khaledgarbaya

**Comment by axe312ger** [comment]
Fine for me. Just make sure the CLI import is optional and has to be added to the `postinstall ` npm script by the boilerplate creator.

**Comment by Khaledgarbaya** [comment]
I think this is a good idea. especially distributing the content

**Comment by floelhoeffel** [comment]
We encourage distribution of the content models through the `Contentful CLI` for the time being.
